### ISSUE TITLE
UIWebView and WKWebView

### ISSUE THREAD

**Issue by hypercrypt** [ShingoFukuyama/WKWebViewTips#1]
Do you have any documentation as to why UIWebView and WKWebView can't co-exist? Any message from Apple or another source?

**Comment by ShingoFukuyama** [comment]
A few Japanese people said they were not able to complete submitting the build which uses UIWebView and WKWebView.

https://twitter.com/k_katsumi/status/516169494083809281
https://twitter.com/tetsuyak_/status/525526523843850240
http://qiita.com/ShingoFukuyama/items/eede79a284c3669846e9

But one of them also said that it's possible to pass the validation if a build only supports iOS8.

**Comment by hypercrypt** [comment]
Thanks!

**Comment by DavidPhillipOster** [comment]
It's quite easy to have a single app that uses UIWebView on iOS 7 and WKWebView on iOS 8 and 9. The Japanese complainers are complaining about frameworks. You can't have a loadable framework in an app that might run on iOS 7.
