### ISSUE TITLE
Disabling long-press menu (ideas)

### ISSUE THREAD

**Issue by winzig** [ShingoFukuyama/WKWebViewTips#5]
Could you run javascript to convert all links on the page to similarly-styled span tags with onclick event handlers?

**Comment by ShingoFukuyama** [comment]
That never crossed my mind.
But it won't prevent appearing WKWebView's action sheet if you start long-pressing a tag.

Detect a specific gesture and invalidate it before appearing the action sheet would work.

**Comment by ShingoFukuyama** [comment]
Is this fixed as of iOS 8.2?

**Comment by ShingoFukuyama** [comment]
I confirmed the bug fixed as of iOS 8.2.
