### ISSUE TITLE
Taking screenshots of WKWebView on OS X

### ISSUE THREAD

**Issue by lemonmojo** [ShingoFukuyama/WKWebViewTips#7]
When trying to take a screenshot of a WKWebView on OS X using techniques that work with other Views and the old WebView class the resulting image is always just white.

This issue is well documented on the internet:
http://stackoverflow.com/questions/30149373/render-off-screen-wkwebview-into-nsimage/32146331#32146331
http://stackoverflow.com/questions/31969950/wkwebview-cachedisplayinrect-screenshot-in-os-x/32146270#32146270
http://stackoverflow.com/questions/24727499/wkwebview-screenshots/32146236#32146236

I've just worked around this by using private(!) APIs of WebKit and published the solution in the following repo: https://github.com/lemonmojo/WKWebView-Screenshot

Feel free to include it in your tips if you want to!

**Comment by ShingoFukuyama** [comment]
Thank you! I've added a link to your repository.
